### ISSUE TITLE
获取在线数据的可能的BUG

### ISSUE THREAD

**Issue by chenzm080** [luozhihao/BootPage#1]
当async=true时
获取到的数据要给tableList时，
你用的是： 
`this.$dispatch('data', response.data)`
response.data获取到的不是应该是：
`{data:[],page_num:''}`;吗
所以应该是： `this.$dispatch('data', response.data.data)`吧！！

**Comment by luozhihao** [comment]
感谢，已修复。之前整理的时候漏掉了。
